plugin/bullets.vim

From `:help abbreviations`:
An abbreviation is only recognized when you type a non-keyword character.
This can also be the `<Esc>` that ends insert mode or the `<CR>` that ends a
command. The non-keyword character which ends the abbreviation is inserted
after the expanded abbreviation. **An exception to this is the character `<C-]>`,
which is used to expand an abbreviation without inserting any extra
characters.**

Make mapped <CR> trigger iabbreviations

---

plugin/bullets.vim

I noticed markdown h2 headings (`##`) were being recognized as bullets because the dot acts as a wildcard.

Escape dot for pandoc lists

---

plugin/bullets.vim

A new global variable `g:bullets_line_spacing` allows leaving blank lines between bulleted lines. If the variable is unset or with a value < 2, new bulleted lines are added 1 line below the previous one -- that is the normal behavior of the plugin. With `let g:bullets_line_spacing = 2` each new bulleted line is added 2 lines below the previous one. And so forth.

Add support for double-spaced bulleted lines

---

doc/bullets.txt
plugin/bullets.vim

Add support for Org mode headers. These are different from bullet lists in that they start with leading asterisks rather than spaces, i.e.
`*** My subsubheader`
rather than
`  * My subsubheader`.
The `[X]` checkboxes are not allowed according to Org mode's syntax, so it warrants it's own regular expression.

Add support for Org mode headers

---

plugin/bullets.vim
spec/bullets_spec.rb

When `ignorecase` is set, the regex for roman bullets are matched to mixed case strings and lowercase strings.

Match case regardless of "ignorecase" option

---

plugin/bullets.vim
spec/bullets_spec.rb

There would be use-cases like:
```
i. the first bullet
ii. the second bullet
iii. the third bullet
```
Also this forces roman bullets to be followed by spaces to prevent:
```
m.example.com is site.
mi. the second line
```
```
vi.stackexchange.com is for Vi and Vim.
vii. the second line
```

Support lowercase roman bullets

---

README.md
plugin/bullets.vim
spec/bullets_spec.rb

This PR adds preliminary support for alphabetic ordered lists. It's currently set to only allow up to two characters (`a.` to `z.` and `aa.` to `zz.`) since I didn't want it mistakenly detecting words at the beginning of a line with hard wrapping and to limit the erroneous detection of alphabetic ordinals when it's really just a bad roman numeral. 
I had to add some logic to differentiate between roman numerals and alphabetical ordinals for cases like `i. ` or `dc. `. I accomplished this by checking whether the previous bullet (assuming roman numerals) is one iteration less than the current bullet. There might be a better way to accomplish this, but it seems to work so far.
I haven't added rspec tests yet, but it's currently passing the existing tests. I suspect some existing tests might …

add alphabetic ordinal support

---

plugin/bullets.vim
spec/alphabetic_bullets_spec.rb

This PR fixes an issue where Bullets got confused about what bullet type list it is in the middle of so at the letter `i` of an Alphabetic list it started adding roman numerals following it:
```
a. one
b. two
c. three
d. four
e. five
f. six
g. seven
h. eight
i. nine
ii. ten
```
What it should have been:
```
a. one
b. two
c. three
d. four
e. five
f. six
g. seven
h. eight
i. nine
j. ten
```
Instead of using an `if` `else` control flow when parsing the bullet, I am now trying to match all possible bullets that satisfy the regex, and then resolve known situations where there are two matches.
This is a relatively big refactor but it sets up a more sustainable pattern for supporting more bullet types in the future.

Fix Alphabetic vs Roman Numeral Bullets Bug

---

README.md
doc/bullets.txt
plugin/bullets.vim

It was cool as a learning tool to understand how vim works but really
did not care to use those - so they were not maintained and updated, nor
do I think anybody else was, and they were conflicting with built-in vim
mappings. So many reasons why I'm happy to see those gone.
[Closes #45]

Remove text objects for bullets

---

README.md
doc/bullets.txt
plugin/bullets.vim
spec/alphabetic_bullets_spec.rb
spec/bullets_spec.rb
spec/nested_bullets_spec.rb
spec/renumber_bullets_spec.rb

Adds the following:
* renumbering for nested lists
* renumbering the entire list containing the cursor (gN in normal mode)
* automatic renumbering of the current list when promoting/demoting (optional via g:bullets_renumber_on_change)
* visual mode promoting and demoting of bullets
* automatic renumbering when inserting a new bullet
* additional tests for new functionality (still needs better coverage)
Fixes the following:
* changes the functionality of indenting when outside of the defined bullet levels: keeps the existing bullet and just indents instead of deleting the bullet since the previous behavior is more unexpected than just indenting.
* code cleanup
* update README and documentation

Add visual mode promoting/demoting, nested renumbering, and auto-renumbering

---

README.md
doc/bullets.txt
plugin/bullets.vim
spec/alphabetic_bullets_spec.rb
spec/bullets_spec.rb
spec/checkboxes_spec.rb
spec/nested_bullets_spec.rb
spec/renumber_bullets_spec.rb

This addresses #61. It is enabled by default, but perhaps it would be better to disable it by default since it is not standard GFM markdown syntax.
Note: this also fixes a bug in parsing checkboxes and renumbering lists containing checkbox bullets

Vimwiki checkboxes

---

plugin/bullets.vim

This PR addresses https://github.com/dkarter/bullets.vim/issues/68.
change_bullet_order calls have been modified to call renumber_whole_list only when required. This makes list indentation *much* faster (~10x improvement).

Only renumber whole list if absolutely required

---

plugin/bullets.vim

Using normal mode commands to insert characters is very slow on my laptop (I am running WSL on windows).
In this PR, I have replaced normal-mode functionality with vim functions, which are faster.
This PR is still a work in progress. I am creating it as a place-holder and so that I can get feedback.

Do not use normal mode to replace / insert text

---

plugin/bullets.vim
spec/checkboxes_spec.rb

This PR handles the case when no checkbox is found.
I may have introduced this bug myself with https://github.com/dkarter/bullets.vim/pull/72 :(

Handle not a checkbox

---

plugin/bullets.vim

**_what_**: This pull request allows for automatic insertion of checkbox bullet types `- [ ]` _and_ `* [ ]`.
**_why_**: From what I can tell, bullets.vim will match either `- [ ]` or `* [ ]` syntax as checkbox bullets (seen in the `match_checkbox_bullet_item()` function). However, when it comes to automatically inserting a new bullet in a list of checkboxes, the `next_chk_bullet()` function only inserts new checkboxes with `- [ ]` syntax, regardless of the style matched in the list.
**_how_**: The proposed change is a one line fix, inserting the first character of the matched checkbox bullet found in `match_checkbox_bullet_item()` as the first character of the next bullet. This enables either of the matched syntax styles to be automatically extended (which seems like the expected …

fix: next checkbox bullet type

---

.gitignore

Thanks for a great plugin!
If this is installed in a personal dotfiles repository, using the new vim plugin installation method, as a git submodule (example with `homesick`):
```sh
cd ~/.homesick/repos/dotfiles
mkdir -p home/.vim/pack/bundle/start
cd home/.vim/pack/bundle/start
git submodule add https://... bullets.vim
```
And then you run `helptags ALL`, the file `doc/tags` will be generated inside the submodule, and appear as "(untracked content)" in the `git status` for the dotfiles repository as a whole.
Simplest fix ever: add `doc/tags` to the `.gitignore` file, and the problem goes away!

Add doc/tags to .gitignore.

---

README.md
plugin/bullets.vim

Closes https://github.com/dkarter/bullets.vim/issues/127
This change introduces two things:
1. `<Plug>...` mappings for easier reuse
2. `g:bullets_custom_mappings` option where you can customize all the key mappings
I added a usage example for new `g:bullets_custom_mappings` option to the README.

Improve key mappings customization

---

plugin/bullets.vim

In this PR I have modified several functions to eliminate the need for modifying the current selection or cursor position.
This results in:
1. Much smaller and cleaner code
2. Reduced chance that selection is accidentally changed when renumbering etc
3. Improved performance in some cases
I have also added logic to explicitly save the cursor / selection position and have it restored after the change.

Do not change selection to update lists

---

plugin/bullets.vim
spec/nested_bullets_spec.rb

In Chinese and some other languages, fullwidth colon is used.

feat: add support for fullwidth colon "："

---

plugin/bullets.vim

We appear to have introduced a bug in #148 where we use functions not available in old vim versions.
Adding fallback logic to solve this. Addressed #149

Bugfix - strcharlen support older vim
